# spring
spring:
  # profiles
  profiles:
    active: local
# framework
framework:
  # swagger
  swagger:
    base-package: com.c.c.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    com.c.c: info
# mybatis plus
mybatis-plus:
  type-aliases-package: com.c.c.entity,com.c.c.model.*
  mapper-locations: classpath:mappers/*Mapper.xml
